version: "3.9"

services:
  go:
    image: golang:1.20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go run main.go"
    environment:
      - OFFLINE=$OFFLINE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.htmx_demo.entrypoints=http"
      - "traefik.http.routers.htmx_demo.rule=Host(`htmx.docker.localhost`)"
      - "traefik.http.services.htmx_demo.loadbalancer.server.port=8081"
      - "traefik.http.routers.htmx_demo.middlewares=redirect-to-https@file"
      - "traefik.http.routers.htmx_demo_secure.entrypoints=https"
      - "traefik.http.routers.htmx_demo_secure.rule=Host(`htmx.docker.localhost`)"
      - "traefik.http.routers.htmx_demo_secure.tls=true"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: htmx
      MYSQL_USER: htmx
      MYSQL_PASSWORD: htmx
